### ISSUE TITLE
idk wtf this scrollbar is for lol

### ISSUE THREAD

**Issue by afrenkai** [CS3733-D24-Team-R/Team-R-Production#223]

**Comment by afrenkai** [comment]
<img width="1280" alt="image" src="https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/97616103/d6307f91-76dd-450f-bd17-c6708a82c066">

**Comment by avstoyanov** [comment]
it's probably overflowing? if not, you're probably on chrome where any "overflow scroll" element will always display a scroll bar
