### ISSUE TITLE
Needs work. Too large on page

### ISSUE THREAD

**Issue by afrenkai** [CS3733-D24-Team-R/Team-R-Production#224]
![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/97616103/02fe9adc-7efd-43bc-ace2-185d53fa2f07)

**Comment by ngolp** [comment]
I think this is more of a scaling issue. Professor Wong said to assume that we will be using a 2560x1440 display. This is how it looks on my display of that resolution. Try turning your display scale back to 100% and check again

![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/144621445/c630abb6-2e01-4943-9b16-0c85a765656b)
