### ISSUE TITLE
Logout should be under staff login

### ISSUE THREAD

**Issue by afrenkai** [CS3733-D24-Team-R/Team-R-Production#226]
<img width="1271" alt="image" src="https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/97616103/07c5a090-b37a-461d-b8ea-013bfb799484">

**Comment by afrenkai** [comment]
NOTE: This is the guest view as of rn

**Comment by ngolp** [comment]
Fixed, should be in dev
