### ISSUE TITLE
Grey bar on left sidebar collapse for map pages only

### ISSUE THREAD

**Issue by ngolp** [CS3733-D24-Team-R/Team-R-Production#248]
Grey sidebar comes back whenever I collapse left sidebar

![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/144621445/346142fb-7ab6-43fe-8a23-16d31f381383)

![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/144621445/e529e298-24a2-4f1a-8902-94c4bbd13ff6)

**Comment by Canpake59** [comment]
Most likely a resolution issue. Works fine on 1080p it seems?
![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/30377331/1d417b1b-4f80-4087-a979-84e18ba7b5c3)
![image](https://github.com/CS3733-D24-Team-R/Team-R-Production/assets/30377331/4d7c0c2a-e7b9-4414-a3ce-57fa31c427c8)

**Comment by Canpake59** [comment]
Technically intended, as the gray is still there when not in the edit page, just hidden because of the <aside>

**Comment by ngolp** [comment]
Ok, I think we can leave this as is. It's a very minor issue that doesn't detract from the experience.
